<?php 
	session_start();
	include('database_connectie.php');

	$sql = "SELECT * FROM Student ";
	$statement = $db_conn->query($sql);
	$row = $statement->fetch();	
	
	$sql1 = "SELECT * FROM Opleiding ";
	$statement1 = $db_conn->query($sql1);
	$row1 = $statement1->fetch();
	
	$sql2 = "SELECT * FROM Werkervaring";
	$statement2 = $db_conn->query($sql2);
	$row2 = $statement2->fetch();
	
	$sql3 = "SELECT * FROM vaardigheden";
	$statement3 = $db_conn->query($sql3);
	$row3 = $statement3->fetch();
	
	$sql4 = "SELECT * FROM Taal ";
	$statement4 = $db_conn->query($sql4);
	$row4 = $statement4->fetchAll(PDO::FETCH_ASSOC );
	
	$sql5 = "SELECT * FROM Hobby";
	$statement5 = $db_conn->query($sql5);
	$row5 = $statement5->fetch();
	
	if (isset($_SESSION['gebruikersnaam'])){
		echo "<a href=update/student.php id=button1> Wijzigen </a>";
		echo "<a href=update/opleiding.php id=button2> Wijzigen</a>";
		echo "<a href=update/werkervaring.php id=button3> Wijzigen</a>";
		echo "<a href=update/vaardigheden.php id=button4> Wijzigen</a>";
		echo "<a href=update/taal.php id=button5> Wijzigen</a>";
		echo "<a href=update/hobby.php id=button6> Wijzigen</a>";
		echo "<p id=welcome>Welcome " . $_SESSION['gebruikersnaam'] . "</p><br>";
		echo "<a href=logout.php id=logout>uitloggen</a>";
	}
	else{
		echo "<a href=login.phtml><button class=login icon-cart><span>inloggen</span></button></a>";
		echo "<a href=contactnl.html><button id=contact>contact</button></a>";
		echo "<div class=dropdown><button class=dropbtn>Taal</button><div class=dropdown-content><a href=engels/enhome.phtml>EN</a></div></div> ";
	}
	
?>
<!DOCTYPE html>
<html>
<head>
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<title>Home</title>
</head>
<body>
	


	<div id="student">
		<table>
			<tr>
				<h3>Student informatie</h3>
				<p> Voor-Achternaam: <?php echo $row["Voornaam"] . " " . $row["Achternaam"];?></p>
				<p>Studentennummer: <?php echo $row["Studentennummer"];?></p>
				<p>Woonplaats: <?php echo $row["Woonplaats"];?></p>
				<p>Geboortedatum: <?php echo $row['Geboortedatum'];?></p>
			</tr>
		</table>
	</div>		
	<div id="opleiding">
		<table>
			<tr>
				<h3>Opleiding</h3>
				<p>School: <?php echo $row1["Soort"]; ?></p>
				<p>Niveau: <?php echo $row1["niveau"]; ?></p>
				<p>Startdatum en einddatum: <?php echo $row1["Startdatum"] . " - " . $row1["Einddatum"]; ?></p>
				<p>Locatie: <?php echo $row1["locatie"]; ?></p>
			</tr>
		</table>
	</div>
	<div id="werkervaring">
		<table>
			<tr>
				<h3>Werkervaring</h3>
				<p>Werkcode: <?php echo $row2["Werkcode"]; ?></p>
				<p>Startdatum en einddatum: <?php echo $row2["Startdatum"] . " - " . $row2["Einddatum"];?></p>
				<p>Type werk: <?php echo $row2["Type"]; ?></p>
			</tr>
		</table>
	</div>
	<div id="vaardigheden">
		<table>
			<tr>
				<h3>Vaardigheden</h3>
				<p>Vaardigheden: <?php echo $row3["Type"];?></p>
				<p>Niveau vaardigheden: <?php echo $row3["Niveau"];?></p>
			</tr>
		</table>
	</div>
	<div id="taal">
		<table>
			<tr>
				<h3>Taal</h3>
				<p>Taal: <?php foreach ($row4 as $row)
{
    echo htmlentities($row['Taal']) . ", ";
} ?></p>
				<p>Niveau taal: <?php foreach ($row4 as $row){
					echo htmlentities($row['Niveau']) . ", ";				
				}?></p>
			</tr>
		</table>
	</div>
	<div id="hobby">
		<table>
			<tr>
				<h3>Hobby</h3>
				<p>Hobby: <?php echo $row5["Hobby"]; ?></p>
			</tr>
		</table>
	</div>
	<img src="images/pc.jpg" id="pic"></img>
</body>
</html>