<?php
//als er op de knop is gedrukt gebeurt de volgende.
if( isset($_POST['submit'])){
    //sessie starten 
    session_start();
    //input in variabel zetten
    $gebruikersnaam = $_POST['gebruikersnaam'];
    $wachtwoord = $_POST['wachtwoord'];
    
    //database connectie maken
    include('database_connectie.php');
    
    //gebruikersnaam selecteren
    $sql = "SELECT * FROM admin WHERE Gebruikersnaam = :gebruikersnaam"; 
    $statement = $db_conn->prepare($sql); 
    $statement->bindParam(":gebruikersnaam", $gebruikersnaam); 
    $statement->execute(); $database_gegevens = $statement->fetch(PDO::FETCH_ASSOC);
    
    //wachtwoord selecteren
    $sql = "SELECT * FROM admin WHERE Wachtwoord = :wachtwoord"; 
    $statement = $db_conn->prepare($sql); 
    $statement->bindParam(":wachtwoord", $wachtwoord); 
    $statement->execute(); $database_gegevens = $statement->fetch(PDO::FETCH_ASSOC);
    
    //data in database in variabel zetten
    $gebruikersnaamdb = $database_gegevens['Gebruikersnaam'];
    $Wachtwoorddb = $database_gegevens['Wachtwoord'];

    // als de gebruikersnaam/wachtwoord gelijk is aan de gebruikersnaam/wachtwoord in de database gebeurt het volgende.
    if($gebruikersnaam==$gebruikersnaamdb && $wachtwoord==$Wachtwoorddb){
        header('Location: home.phtml');
    }
    //als de gebruikersnaam/wachtwoord niet gelijk is aan de gebruikersnaam/wachtwoord in de database gebeurt het volgende.
    elseif($gebruikersnaamdb!=$gebruikersnaam || $Wachtwoorddb!=$wachtwoord){
        echo '<p style=text-align:center;>'."Oeps! uw gegevens kloppen niet vul het opnieuw in.".'</p>';
    
    }
        //sessie gebruikersnaam onthouden en meenemen.
        $_SESSION['gebruikersnaam'] = $gebruikersnaam;
}
?>
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="css/styleslogin.css">
    <title>Admin inloggen</title>
</head>
<body>
    <div class="wrapper">
	<div class="container">
		<h1>Welcome</h1>
    <form method="post">
        <p>Gebruikersnaam</p>
        <input type="text" name="gebruikersnaam" placeholder="gebruikersnaam" required>
        <p>Wachtwoord</p>
        <input type="password" name="wachtwoord" required><br><br>
        <input class="login" type="submit" name="submit" value="inloggen">
    </form>
    </div>

    
    <ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
	</div>

</body>
</html>
